import React, { useEffect, useMemo, useState } from "react";
import "../css/admin.css";

const BASE = "https://riverra-backend.vercel.app/api";
const API = `${BASE}/members`;
const empty = { id:"", first_name:"", last_name:"", gender:"male", role:"", generation:1, status:"Living", photo:"", biography:"", occupation:"", father_id:"", mother_id:"", spouse_id:"" };
const stamp = (user, action) => ({ audit_action:action, audit_by:user.name, audit_at:new Date().toISOString() });

export default function Admin(){
  const [users,setUsers]=useState([]);
  const [user,setUser]=useState(()=>JSON.parse(sessionStorage.getItem("riverra-user")||"null"));
  const [authMode,setAuthMode]=useState("login");
  const [members,setMembers]=useState(()=>JSON.parse(localStorage.getItem("riverra-family")||"[]"));
  const [gallery,setGallery]=useState(()=>JSON.parse(localStorage.getItem("riverra-gallery")||"[]"));
  const [form,setForm]=useState(empty),[editing,setEditing]=useState(false),[tab,setTab]=useState("family"),[query,setQuery]=useState(""),[notice,setNotice]=useState(null);
  const notify=(message,type="success")=>{setNotice({message,type});setTimeout(()=>setNotice(null),3500)};
  const persistMembers=n=>{setMembers(n);localStorage.setItem("riverra-family",JSON.stringify(n))};
  const canMembers=user&&["PJ Server","PJ Universal","Super Admin"].includes(user.level);
  const canGallery=user&&["PJ Universal","Super Admin"].includes(user.level);
  const isSuper=user?.level==="Super Admin";
  useEffect(()=>{fetch(API).then(r=>r.json()).then(r=>{const d=Array.isArray(r)?r:r.data;if(Array.isArray(d))persistMembers(d)}).catch(()=>{})},[]);
  useEffect(()=>{if(!isSuper)return;fetch(`${BASE}/admins`,{headers:{Authorization:`Bearer ${user.token}`}}).then(async r=>{const out=await r.json();if(!r.ok)throw new Error(out.message);setUsers(out.data.map(x=>({...x,level:x.role||"Belum ditentukan",active:x.is_active}))) }).catch(e=>notify(e.message,"error"))},[isSuper,user?.token]);
  const filtered=useMemo(()=>members.filter(m=>`${m.first_name} ${m.last_name}`.toLowerCase().includes(query.toLowerCase())),[members,query]);
  const login=async e=>{e.preventDefault();try{const r=await fetch(`${BASE}/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:e.target.email.value,password:e.target.password.value})});const out=await r.json();if(!r.ok)throw new Error(out.message);const u={...out.data.user,level:out.data.user.role,token:out.data.token};sessionStorage.setItem("riverra-user",JSON.stringify(u));setUser(u)}catch(err){notify(err.message||"Login gagal.","error")}};
  const register=async e=>{e.preventDefault();const fd=new FormData(e.target);try{const r=await fetch(`${BASE}/auth/register`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:fd.get("name"),email:fd.get("email"),password:fd.get("password")})});const out=await r.json();if(!r.ok)throw new Error(out.message);setAuthMode("login");notify(out.message)}catch(err){notify(err.message||"Registrasi gagal.","error")}};
  const submit=async e=>{e.preventDefault();if(!canMembers)return notify("Anda tidak memiliki akses.","error");const item={...form,id:Number(form.id)||Date.now(),generation:Number(form.generation),father_id:form.father_id||null,mother_id:form.mother_id||null,spouse_id:form.spouse_id||null,...stamp(user,editing?"edited":"created")};const payload={firstName:item.first_name,lastName:item.last_name,gender:item.gender,generation:item.generation,status:item.status,photo:item.photo,biography:item.biography,occupation:item.occupation,role:item.role,fatherId:item.father_id,motherId:item.mother_id,spouseId:item.spouse_id};try{const r=await fetch(editing?`${API}/${item.id}`:API,{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${user.token}`},body:JSON.stringify(payload)});const out=await r.json();if(!r.ok||out.success===false)throw new Error(out.message||"Backend menolak data");Object.assign(item,out.data||{})}catch(err){notify(`Backend: ${err.message}`,"error");return}persistMembers(editing?members.map(x=>x.id===item.id?item:x):[...members,item]);notify(editing?"Data berhasil diedit.":"Data berhasil ditambahkan.");setForm(empty);setEditing(false)};
  const remove=async id=>{if(!confirm("Hapus anggota ini secara permanen?"))return;try{const r=await fetch(`${API}/${id}`,{method:"DELETE",headers:{"Authorization":`Bearer ${user.token}`}});if(!r.ok)throw new Error("Backend gagal menghapus");persistMembers(members.filter(x=>x.id!==id));notify("Data berhasil dihapus.")}catch(e){notify(e.message,"error")}};
  const upload=e=>[...e.target.files].forEach(file=>{const rd=new FileReader();rd.onload=()=>{const n=[...gallery,{id:Date.now()+Math.random(),name:file.name,src:rd.result,...stamp(user,"uploaded")}];setGallery(n);localStorage.setItem("riverra-gallery",JSON.stringify(n));notify("Foto berhasil di-upload.")};rd.readAsDataURL(file)});
  const updateAccess=async(id,changes)=>{try{const current=users.find(x=>x.id===id);const r=await fetch(`${BASE}/admins/${id}/access`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${user.token}`},body:JSON.stringify({role:changes.level||current.level,isActive:changes.active??current.active})});const out=await r.json();if(!r.ok)throw new Error(out.message);setUsers(users.map(x=>x.id===id?{...x,level:out.data.role||"Belum ditentukan",active:out.data.is_active}:x));notify("Akses admin berhasil diperbarui.")}catch(e){notify(e.message,"error")}};
  const deleteAdmin=async id=>{if(!confirm("Hapus akun admin ini secara permanen?"))return;try{const r=await fetch(`${BASE}/admins/${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${user.token}`}});const out=await r.json();if(!r.ok)throw new Error(out.message);setUsers(users.filter(x=>x.id!==id));notify("Akun admin berhasil dihapus.")}catch(e){notify(e.message,"error")}};
  if(!user)return <main className="admin-page login">{notice&&<div className={`admin-notice ${notice.type}`}>{notice.message}</div>}<div className="admin-card"><p className="eyebrow">RIVERRA / SECURE ACCESS</p><h1>{authMode==="login"?"Admin portal":"Registrasi admin"}</h1>{authMode==="login"?<form onSubmit={login}><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" required/><button>Masuk</button><button type="button" className="ghost" onClick={()=>setAuthMode("register")}>Buat akun</button><small>Super Admin demo: admin@riverra.com / riverra</small></form>:<form onSubmit={register}><input name="name" placeholder="Nama lengkap" required/><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" minLength="6" required/><button>Daftar</button><button type="button" className="ghost" onClick={()=>setAuthMode("login")}>Kembali</button></form>}</div></main>;
  return <main className="admin-page">{notice&&<div className={`admin-notice ${notice.type}`}>{notice.message}</div>}<div className="admin-head"><div><p className="eyebrow">{user.level}</p><h1>Family archives</h1><p>Masuk sebagai {user.name}</p></div><button className="ghost" onClick={()=>{sessionStorage.removeItem("riverra-user");setUser(null)}}>Keluar</button></div><div className="admin-tabs"><button className={tab==="family"?"selected":""} onClick={()=>setTab("family")}>Family tree <span>{members.length}</span></button>{canGallery&&<button className={tab==="gallery"?"selected":""} onClick={()=>setTab("gallery")}>Gallery <span>{gallery.length}</span></button>}{isSuper&&<button className={tab==="access"?"selected":""} onClick={()=>setTab("access")}>Akses admin <span>{users.length}</span></button>}</div>
  {tab==="family"&&<section className="admin-grid"><form className="admin-card member-form" onSubmit={submit}><h2>{editing?"Edit anggota":"Tambah anggota"}</h2><div className="form-grid">{[["first_name","Nama depan"],["last_name","Nama belakang"],["role","Peran / gelar"],["occupation","Pekerjaan"],["generation","Generasi"],["father_id","ID ayah"],["mother_id","ID ibu"],["spouse_id","ID pasangan"]].map(([k,l])=><label key={k}>{l}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required={k==="first_name"}/></label>)}</div><label>Gender<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option>male</option><option>female</option><option>other</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Living</option><option>Deceased</option></select></label><label>Biografi<textarea value={form.biography} onChange={e=>setForm({...form,biography:e.target.value})}/></label><label>Foto URL<input value={form.photo} onChange={e=>setForm({...form,photo:e.target.value})}/></label><button>{editing?"Simpan perubahan":"Tambah anggota"}</button></form><div className="admin-card"><div className="member-list-head"><h2>Anggota terdaftar</h2><input className="search-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari nama..."/></div>{filtered.map(m=><div className="member-row" key={m.id}><div><b>{m.first_name} {m.last_name}</b><small>{m.role} · Gen {m.generation}</small>{m.audit_by&&<small className="audit">{m.audit_action} by: {m.audit_by}, {new Date(m.audit_at).toLocaleString("id-ID")}</small>}</div><button onClick={()=>{setForm({...empty,...m});setEditing(true)}}>Edit</button><button className="danger" onClick={()=>remove(m.id)}>Hapus</button></div>)}</div></section>}
  {tab==="gallery"&&canGallery&&<section className="admin-card"><h2>Upload foto galeri</h2><label className="upload-box">Pilih foto<input type="file" accept="image/*" multiple onChange={upload}/></label><div className="gallery-grid">{gallery.map(g=><figure key={g.id}><img src={g.src}/><figcaption><span>{g.name}<small className="audit">{g.audit_action} by: {g.audit_by}, {new Date(g.audit_at).toLocaleString("id-ID")}</small></span><button onClick={()=>{const n=gallery.filter(x=>x.id!==g.id);setGallery(n);localStorage.setItem("riverra-gallery",JSON.stringify(n))}}>×</button></figcaption></figure>)}</div></section>}
  {tab==="access"&&isSuper&&<section className="admin-card"><h2>Manajemen akses admin</h2>{users.map(u=><div className="access-row" key={u.id}><div><b>{u.name}</b><small>{u.email}</small></div><select value={u.level} disabled={u.id===user.id} onChange={e=>updateAccess(u.id,{level:e.target.value})}><option>Belum ditentukan</option><option>PJ Server</option><option>PJ Universal</option><option>Super Admin</option></select><button disabled={u.id===user.id} onClick={()=>updateAccess(u.id,{active:!u.active})}>{u.active?"Cabut akses":"Berikan akses"}</button>{u.id!==user.id&&<button className="danger" onClick={()=>{if(confirm("Hapus akun ini?"))persistUsers(users.filter(x=>x.id!==u.id))}}>Hapus akun</button>}</div>)}</section>}</main>;
}
